#INCLUDE "PROTHEUS.CH"
#INCLUDE "APWEBSRV.CH"

/* ===============================================================================
WSDL Location    \tmptdsspon3733\WSINFOCONHECPROTHEUSWMS_apw.wsdl
Gerado em        01/27/16 13:38:15
Observações      Código-Fonte gerado por ADVPL WSDL Client 1.120703
                 Alterações neste arquivo podem causar funcionamento incorreto
                 e serão perdidas caso o código-fonte seja gerado novamente.
=============================================================================== */

User Function _IODOEDR ; Return  // "dummy" function - Internal Use 

/* -------------------------------------------------------------------------------
WSDL Service WSWSINFOCONHECPROTHEUSWMS
------------------------------------------------------------------------------- */

WSCLIENT WSWSINFOCONHECPROTHEUSWMS

	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD RESET
	WSMETHOD CLONE
	WSMETHOD INTEGR_PROTHEUS_WMS_LOGIX_INFCONHEC

	WSDATA   _URL                      AS String
	WSDATA   _HEADOUT                  AS Array of String
	WSDATA   _COOKIES                  AS Array of String
	WSDATA   oWSINFOCONHECIMENTO       AS WSINFOCONHECPROTHEUSWMS_OWSSTRUCTINFOCONHECIMENTO
	WSDATA   oWSINTEGR_PROTHEUS_WMS_LOGIX_INFCONHECRESULT AS WSINFOCONHECPROTHEUSWMS_OWSSTRUCTINFOCONHECIMENTOSTAT

	// Estruturas mantidas por compatibilidade - NÃO USAR
	WSDATA   oWSOWSSTRUCTINFOCONHECIMENTO AS WSINFOCONHECPROTHEUSWMS_OWSSTRUCTINFOCONHECIMENTO

ENDWSCLIENT

WSMETHOD NEW WSCLIENT WSWSINFOCONHECPROTHEUSWMS
::Init()
If !FindFunction("XMLCHILDEX")
	UserException("O Código-Fonte Client atual requer os executáveis do Protheus Build [7.00.131227A-20150602] ou superior. Atualize o Protheus ou gere o Código-Fonte novamente utilizando o Build atual.")
EndIf
Return Self

WSMETHOD INIT WSCLIENT WSWSINFOCONHECPROTHEUSWMS
	::oWSINFOCONHECIMENTO := WSINFOCONHECPROTHEUSWMS_OWSSTRUCTINFOCONHECIMENTO():New()
	::oWSINTEGR_PROTHEUS_WMS_LOGIX_INFCONHECRESULT := WSINFOCONHECPROTHEUSWMS_OWSSTRUCTINFOCONHECIMENTOSTAT():New()

	// Estruturas mantidas por compatibilidade - NÃO USAR
	::oWSOWSSTRUCTINFOCONHECIMENTO := ::oWSINFOCONHECIMENTO
Return

WSMETHOD RESET WSCLIENT WSWSINFOCONHECPROTHEUSWMS
	::oWSINFOCONHECIMENTO := NIL 
	::oWSINTEGR_PROTHEUS_WMS_LOGIX_INFCONHECRESULT := NIL 

	// Estruturas mantidas por compatibilidade - NÃO USAR
	::oWSOWSSTRUCTINFOCONHECIMENTO := NIL
	::Init()
Return

WSMETHOD CLONE WSCLIENT WSWSINFOCONHECPROTHEUSWMS
Local oClone := WSWSINFOCONHECPROTHEUSWMS():New()
	oClone:_URL          := ::_URL 
	oClone:oWSINFOCONHECIMENTO :=  IIF(::oWSINFOCONHECIMENTO = NIL , NIL ,::oWSINFOCONHECIMENTO:Clone() )
	oClone:oWSINTEGR_PROTHEUS_WMS_LOGIX_INFCONHECRESULT :=  IIF(::oWSINTEGR_PROTHEUS_WMS_LOGIX_INFCONHECRESULT = NIL , NIL ,::oWSINTEGR_PROTHEUS_WMS_LOGIX_INFCONHECRESULT:Clone() )

	// Estruturas mantidas por compatibilidade - NÃO USAR
	oClone:oWSOWSSTRUCTINFOCONHECIMENTO := oClone:oWSINFOCONHECIMENTO
Return oClone

// WSDL Method INTEGR_PROTHEUS_WMS_LOGIX_INFCONHEC of Service WSWSINFOCONHECPROTHEUSWMS

WSMETHOD INTEGR_PROTHEUS_WMS_LOGIX_INFCONHEC WSSEND oWSINFOCONHECIMENTO WSRECEIVE oWSINTEGR_PROTHEUS_WMS_LOGIX_INFCONHECRESULT WSCLIENT WSWSINFOCONHECPROTHEUSWMS
Local cSoap := "" , oXmlRet

BEGIN WSMETHOD

cSoap += '<INTEGR_PROTHEUS_WMS_LOGIX_INFCONHEC xmlns="http://www.totvs.com/">'
cSoap += WSSoapValue("INFOCONHECIMENTO", ::oWSINFOCONHECIMENTO, oWSINFOCONHECIMENTO , "OWSSTRUCTINFOCONHECIMENTO", .T. , .F., 0 , NIL, .F.) 
cSoap += "</INTEGR_PROTHEUS_WMS_LOGIX_INFCONHEC>"

oXmlRet := SvcSoapCall(	Self,cSoap,; 
	"http://www.totvs.com/INTEGR_PROTHEUS_WMS_LOGIX_INFCONHEC",; 
	"DOCUMENT","http://www.totvs.com/",,"1.031217",; 
	"http://10.80.74.85:8090/WSINFOCONHECPROTHEUSWMS.apw")

::Init()
::oWSINTEGR_PROTHEUS_WMS_LOGIX_INFCONHECRESULT:SoapRecv( WSAdvValue( oXmlRet,"_INTEGR_PROTHEUS_WMS_LOGIX_INFCONHECRESPONSE:_INTEGR_PROTHEUS_WMS_LOGIX_INFCONHECRESULT","OWSSTRUCTINFOCONHECIMENTOSTAT",NIL,NIL,NIL,NIL,NIL,NIL) )

END WSMETHOD

oXmlRet := NIL
Return .T.


// WSDL Data Structure OWSSTRUCTINFOCONHECIMENTO

WSSTRUCT WSINFOCONHECPROTHEUSWMS_OWSSTRUCTINFOCONHECIMENTO
	WSDATA   cCCHAVEACESSO             AS string
	WSDATA   cCCNPJDESTINATARIO        AS string
	WSDATA   cCCNPJEMISSOR             AS string
	WSDATA   cCCNPJREMETENTE           AS string
	WSDATA   cCFILIALCONHECIMENTO      AS string
	WSDATA   cCNUMCONHECIMENTO         AS string
	WSDATA   cCSERIECONHECIMENTO       AS string
	WSDATA   cCSITUACAO                AS string
	WSDATA   dDDATAEMISSAO             AS date
	WSDATA   nNQTDVOLUMES              AS integer
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPSEND
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSINFOCONHECPROTHEUSWMS_OWSSTRUCTINFOCONHECIMENTO
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSINFOCONHECPROTHEUSWMS_OWSSTRUCTINFOCONHECIMENTO
Return

WSMETHOD CLONE WSCLIENT WSINFOCONHECPROTHEUSWMS_OWSSTRUCTINFOCONHECIMENTO
	Local oClone := WSINFOCONHECPROTHEUSWMS_OWSSTRUCTINFOCONHECIMENTO():NEW()
	oClone:cCCHAVEACESSO        := ::cCCHAVEACESSO
	oClone:cCCNPJDESTINATARIO   := ::cCCNPJDESTINATARIO
	oClone:cCCNPJEMISSOR        := ::cCCNPJEMISSOR
	oClone:cCCNPJREMETENTE      := ::cCCNPJREMETENTE
	oClone:cCFILIALCONHECIMENTO := ::cCFILIALCONHECIMENTO
	oClone:cCNUMCONHECIMENTO    := ::cCNUMCONHECIMENTO
	oClone:cCSERIECONHECIMENTO  := ::cCSERIECONHECIMENTO
	oClone:cCSITUACAO           := ::cCSITUACAO
	oClone:dDDATAEMISSAO        := ::dDDATAEMISSAO
	oClone:nNQTDVOLUMES         := ::nNQTDVOLUMES
Return oClone

WSMETHOD SOAPSEND WSCLIENT WSINFOCONHECPROTHEUSWMS_OWSSTRUCTINFOCONHECIMENTO
	Local cSoap := ""
	cSoap += WSSoapValue("CCHAVEACESSO", ::cCCHAVEACESSO, ::cCCHAVEACESSO , "string", .T. , .F., 0 , NIL, .F.) 
	cSoap += WSSoapValue("CCNPJDESTINATARIO", ::cCCNPJDESTINATARIO, ::cCCNPJDESTINATARIO , "string", .T. , .F., 0 , NIL, .F.) 
	cSoap += WSSoapValue("CCNPJEMISSOR", ::cCCNPJEMISSOR, ::cCCNPJEMISSOR , "string", .T. , .F., 0 , NIL, .F.) 
	cSoap += WSSoapValue("CCNPJREMETENTE", ::cCCNPJREMETENTE, ::cCCNPJREMETENTE , "string", .T. , .F., 0 , NIL, .F.) 
	cSoap += WSSoapValue("CFILIALCONHECIMENTO", ::cCFILIALCONHECIMENTO, ::cCFILIALCONHECIMENTO , "string", .T. , .F., 0 , NIL, .F.) 
	cSoap += WSSoapValue("CNUMCONHECIMENTO", ::cCNUMCONHECIMENTO, ::cCNUMCONHECIMENTO , "string", .T. , .F., 0 , NIL, .F.) 
	cSoap += WSSoapValue("CSERIECONHECIMENTO", ::cCSERIECONHECIMENTO, ::cCSERIECONHECIMENTO , "string", .T. , .F., 0 , NIL, .F.) 
	cSoap += WSSoapValue("CSITUACAO", ::cCSITUACAO, ::cCSITUACAO , "string", .T. , .F., 0 , NIL, .F.) 
	cSoap += WSSoapValue("DDATAEMISSAO", ::dDDATAEMISSAO, ::dDDATAEMISSAO , "date", .T. , .F., 0 , NIL, .F.) 
	cSoap += WSSoapValue("NQTDVOLUMES", ::nNQTDVOLUMES, ::nNQTDVOLUMES , "integer", .T. , .F., 0 , NIL, .F.) 
Return cSoap

// WSDL Data Structure OWSSTRUCTINFOCONHECIMENTOSTAT

WSSTRUCT WSINFOCONHECPROTHEUSWMS_OWSSTRUCTINFOCONHECIMENTOSTAT
	WSDATA   nCSTAT                    AS integer
	WSDATA   cXMOTIVO                  AS string
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT

WSMETHOD NEW WSCLIENT WSINFOCONHECPROTHEUSWMS_OWSSTRUCTINFOCONHECIMENTOSTAT
	::Init()
Return Self

WSMETHOD INIT WSCLIENT WSINFOCONHECPROTHEUSWMS_OWSSTRUCTINFOCONHECIMENTOSTAT
Return

WSMETHOD CLONE WSCLIENT WSINFOCONHECPROTHEUSWMS_OWSSTRUCTINFOCONHECIMENTOSTAT
	Local oClone := WSINFOCONHECPROTHEUSWMS_OWSSTRUCTINFOCONHECIMENTOSTAT():NEW()
	oClone:nCSTAT               := ::nCSTAT
	oClone:cXMOTIVO             := ::cXMOTIVO
Return oClone

WSMETHOD SOAPRECV WSSEND oResponse WSCLIENT WSINFOCONHECPROTHEUSWMS_OWSSTRUCTINFOCONHECIMENTOSTAT
	::Init()
	If oResponse = NIL ; Return ; Endif 
	::nCSTAT             :=  WSAdvValue( oResponse,"_CSTAT","integer",NIL,"Property nCSTAT as s:integer on SOAP Response not found.",NIL,"N",NIL,NIL) 
	::cXMOTIVO           :=  WSAdvValue( oResponse,"_XMOTIVO","string",NIL,"Property cXMOTIVO as s:string on SOAP Response not found.",NIL,"S",NIL,NIL) 
Return


