#ifdef SPANISH
	#define STR0001 "Cálculo Consolidado" 
	#define STR0002 "Este programa tem como objetivo efetuar o Cálculo Consolidado das Avaliações (Competências, Me-"
	#define STR0003 "tas e Formação Acadêmica), com base no critério estabelecido em 'Parâmetros'"
	#define STR0004 "Processamento Concluído"
	#define STR0005 "_GravaLog - Não foi possivel criar o arquivo de Log."
	#define STR0006 "O Período informado ainda encontra-se aberto para Manutenção dos Resultados. (Campo RDU_FIMRES)"
	#define STR0007 "Período"
	#define STR0008 "Falha na cópia do arquivo "
	#define STR0009 " para visualização. O arquivo estará disponível na pasta '\SYSTEM\' do Servidor."
	#define STR0010 "LISTA DE REGISTROS PROCESSADOS COM SUCESSO"
	#define STR0011 "LISTA DE REGISTROS PROCESSADOS SEM RESULTADO INFORMADO PELO GESTOR"
	#define STR0012 "Filial"
	#define STR0013 "Matrícula"
	#define STR0014 "Nome"
	#define STR0015 "Parâmetros"
	#define STR0016 "Meta(s)"
	#define STR0017 "Processo concluído! Clique em 'Confirmar' para mais detalhes."
	#define STR0018 "Resumo: "
	#define STR0019 "Registros Processados: "
	#define STR0020 "Resultados Zerados: "
	#define STR0021 "Data/Hora de Término do Processamento: "
	#define STR0022 "Data/Hora de Início do Processamento: "
	#define STR0023 "Parâmetros: "
	#define STR0024 "Período: "
	#define STR0025 "Matrícula(s): "
	#define STR0026 "Reprocessa?: " 
	#define STR0027 "Sim"
	#define STR0028 "Não"
	#define STR0029 "Perguntas"
#else
	#ifdef ENGLISH
		#define STR0001 "Cálculo Consolidado" 
		#define STR0002 "Este programa tem como objetivo efetuar o Cálculo Consolidado das Avaliações (Competências, Me-"
		#define STR0003 "tas e Formação Acadêmica), com base no critério estabelecido em 'Parâmetros'"
		#define STR0004 "Processamento Concluído"
		#define STR0005 "_GravaLog - Não foi possivel criar o arquivo de Log."
		#define STR0006 "O Período informado ainda encontra-se aberto para Manutenção dos Resultados. (Campo RDU_FIMRES)"
		#define STR0007 "Período"
		#define STR0008 "Falha na cópia do arquivo "
		#define STR0009 " para visualização. O arquivo estará disponível na pasta '\SYSTEM\' do Servidor."
		#define STR0010 "LISTA DE REGISTROS PROCESSADOS COM SUCESSO"
		#define STR0011 "LISTA DE REGISTROS PROCESSADOS SEM RESULTADO INFORMADO PELO GESTOR"
		#define STR0012 "Filial"
		#define STR0013 "Matrícula"
		#define STR0014 "Nome"
		#define STR0015 "Parâmetros"
		#define STR0016 "Meta(s)"
		#define STR0017 "Processo concluído! Clique em 'Confirmar' para mais detalhes."
		#define STR0018 "Resumo: "
		#define STR0019 "Registros Processados: "
		#define STR0020 "Resultados Zerados: "
		#define STR0021 "Data/Hora de Término do Processamento: "
		#define STR0022 "Data/Hora de Início do Processamento: "
		#define STR0023 "Parâmetros: "
		#define STR0024 "Período: "
		#define STR0025 "Matrícula(s): "
		#define STR0026 "Reprocessa?: " 
		#define STR0027 "Sim"
		#define STR0028 "Não"
		#define STR0029 "Perguntas"
	#else
		#define STR0001 "Cálculo Consolidado" 
		#define STR0002 "Este programa tem como objetivo efetuar o Cálculo Consolidado das Avaliações (Competências, Me-"
		#define STR0003 "tas e Formação Acadêmica), com base no critério estabelecido em 'Parâmetros'"
		#define STR0004 "Processamento Concluído"
		#define STR0005 "_GravaLog - Não foi possivel criar o arquivo de Log."
		#define STR0006 "O Período " + cPeriodo + " - " + AllTrim(RDU->RDU_DESC) + ", utilizado na Política informada, ainda encontra-se aberto para Manutenção dos Resultados. (Campo RDU_FIMRES)"
		#define STR0007 "Período"
		#define STR0008 "Falha na cópia do arquivo "
		#define STR0009 " para visualização. O arquivo estará disponível na pasta '\SYSTEM\' do Servidor."
		#define STR0010 "LISTA DE REGISTROS PROCESSADOS COM SUCESSO"
		#define STR0011 "LISTA DE REGISTROS PROCESSADOS SEM RESULTADO INFORMADO PELO GESTOR"
		#define STR0012 "Filial"
		#define STR0013 "Matrícula"
		#define STR0014 "Nome"
		#define STR0015 "Parâmetros"
		#define STR0016 "Meta(s)"
		#define STR0017 "Processo concluído! Clique em 'Confirmar' para mais detalhes."
		#define STR0018 "Resumo: "
		#define STR0019 "Registros Processados: "
		#define STR0020 "Resultados Zerados: "
		#define STR0021 "Data/Hora de Término do Processamento: "
		#define STR0022 "Data/Hora de Início do Processamento: "
		#define STR0023 "Parâmetros: "
		#define STR0024 "Período: "
		#define STR0025 "Matrícula(s): "
		#define STR0026 "Reprocessa?: " 
		#define STR0027 "Sim"
		#define STR0028 "Não"
		#define STR0029 "Perguntas"
	#endif
#endif
